version: "3"
services:
  reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfile # to jump into container use ash instead of bin/bash
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" 
      - "./production_traefik:/etc/traefik/acme:z"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--api.insecure=true"
