# Global configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: true

# API and dashboard configuration
api:
  dashboard: true
  insecure: true
  debug: true

# Logging configuration
log:
  level: DEBUG

# Entry points configuration
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# Certificates resolvers configuration
certificatesResolvers:
  letsencrypt:
    acme:
      email: "hantsawilliams@gmail.com"
      storage: "/etc/traefik/acme/acme.json"
      httpChallenge:
        entryPoint: web

# Providers configuration
providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true


# HTTP routers configuration

# linting: disable=yaml.schema
# yaml-ls: disable=SCHEMA_VALIDATION
http:

  routers:

    # traefik dashboard
    router-1:
      rule: "Host(`traefik.hantswilliams.com`) && Path(`/`)"
      service: "api@internal"
      entryPoints:
        - "web"

    # flask app #1 - main/root page 
    router-2:
      rule: "Host(`hantswilliams.com`) || Host(`www.hantswilliams.com`)"
      service: "service-2"
      entryPoints:
        - "web"

    # flask app #2 - subdomain 1 
    router-3:
      rule: "Host(`app1.hantswilliams.com`)"
      service: "service-3"
      tls:
        certResolver: "letsencrypt"
      entryPoints:
        - "web"
        - "websecure"

    # flask app #3 - subdomain 2
    router-4:
      rule: "Host(`app2.hantswilliams.com`)"
      service: "service-4"
      tls:
        certResolver: "letsencrypt"
      entryPoints:
        - "web"
        - "websecure"

  # HTTP services configuration
  services:
    service-2:
      loadBalancer:
        servers:
          - url: "http://34.171.76.221:80"
      
    service-3:
      loadBalancer:
        servers:
          - url: "http://34.170.61.70:80"

    service-4:
      loadBalancer:
        servers:
          - url: "http://35.194.42.230:80"



    


