# Global configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: true

# API and dashboard configuration
api:
  dashboard: true
  insecure: true
  debug: true

# Logging configuration
log:
  level: DEBUG

# Entry points configuration
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# Providers configuration
providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true

# HTTP routers configuration
http:

  routers:

    router-1:
      rule: "Host(`hantswilliams.com`)"
      service: "service-1"
      entryPoints:
        - "web"

    router-2:
      rule: "Host(`app1.hantswilliams.com`)"
      service: "service-2"
      entryPoints:
        - "web"

    router-3:
      rule: "Host(`traefik.hantswilliams.com`) && Path(`/`)"
      service: "api@internal"
      entryPoints:
        - "web"

    router-4:
      rule: "Host(`app2.hantswilliams.com`) && PathPrefix(`/dashboard/`)"
      service: "service-4"
      entryPoints:
        - "web"


  # HTTP services configuration
  services:
    service-1:
      loadBalancer:
        servers:
          - url: "http://34.171.76.221:80"
      
    service-2:
      loadBalancer:
        servers:
          - url: "http://34.170.61.70:80"

    service-4:
      loadBalancer:
        servers:
          - url: "http://35.194.42.230:80"



    


